import matplotlib.pyplot as plt
import pandas as pd
dev = pd.read_csv("/Users/mayankarora/Documents/sem 7/sustainable-prediction/Bert-csv/bert-results - developed.csv")
developing = pd.read_csv("/Users/mayankarora/Documents/sem 7/sustainable-prediction/Bert-csv/bert-results - developing.csv")
under = pd.read_csv("/Users/mayankarora/Documents/sem 7/sustainable-prediction/Bert-csv/bert-results - under.csv")

fig , ax = plt.subplots(5,1,figsize = (15,15))
fig.suptitle("BERT model on developed countries dataset")
ax[0].plot(dev['Step'] , dev['Training Loss'],color = 'blue' , label = "training loss")
ax[1].plot(dev['Step'] , dev['Validation Loss'],color = 'black' , label = "Validation loss")
ax[2].plot(dev['Step'] , dev['F1'],color = 'orange' , label = "F1")
ax[3].plot(dev['Step'] , dev['Precision'],color = 'green' , label = "Precision")
ax[4].plot(dev['Step'] , dev['Recall'],color = 'magenta' , label = "Recall")
ax[0].set_ylabel("Training loss")
ax[1].set_ylabel("Validation loss")
ax[2].set_ylabel("F1")
ax[3].set_ylabel("Precision")
ax[4].set_ylabel("Recall")
ax[4].set_xlabel("Steps")
ax[0].legend()
ax[1].legend()
ax[2].legend()
ax[3].legend()
ax[4].legend()


fig1 , ax2 = plt.subplots(5,1,figsize = (15,15))
fig1.suptitle("BERT model on developing countries dataset")
ax2[0].plot(developing['Step'] , developing['Training Loss'],color = 'blue' , label = "training loss")
ax2[1].plot(developing['Step'] , developing['Validation Loss'],color = 'black' , label = "Validation loss")
ax2[2].plot(developing['Step'] , developing['F1'],color = 'orange' , label = "F1")
ax2[3].plot(developing['Step'] , developing['Precision'],color = 'green' , label = "Precision")
ax2[4].plot(developing['Step'] , developing['Recall'],color = 'magenta' , label = "Recall")
ax2[0].set_ylabel("Training loss")
ax2[1].set_ylabel("Validation loss")
ax2[2].set_ylabel("F1")
ax2[3].set_ylabel("Precision")
ax2[4].set_ylabel("Recall")
ax2[4].set_xlabel("Steps")
ax2[0].legend()
ax2[1].legend()
ax2[2].legend()
ax2[3].legend()
ax2[4].legend()

fig2 , ax3 = plt.subplots(5,1,figsize = (15,15))
fig2.suptitle("BERT model on under-developed countries dataset")
ax3[0].plot(under['Step'] , under['Training Loss'],color = 'blue' , label = "training loss")
ax3[1].plot(under['Step'] , under['Validation Loss'],color = 'black' , label = "Validation loss")
ax3[2].plot(under['Step'] , under['F1'],color = 'orange' , label = "F1")
ax3[3].plot(under['Step'] , under['Precision'],color = 'green' , label = "Precision")
ax3[4].plot(under['Step'] , under['Recall'],color = 'magenta' , label = "Recall")
ax3[0].set_ylabel("Training loss")
ax3[1].set_ylabel("Validation loss")
ax3[2].set_ylabel("F1")
ax3[3].set_ylabel("Precision")
ax3[4].set_ylabel("Recall")
ax3[4].set_xlabel("Steps")
ax3[0].legend()
ax3[1].legend()
ax3[2].legend()
ax3[3].legend()
ax3[4].legend()